name: 03 Build & Push to ECR

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
env:
  IMAGE_NAME: tiny-health-app
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

jobs:
   verify:
    # The runner is the temporary machine that executes the steps below.
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        # Download the repository contents onto the runner.
        uses: actions/checkout@v6

      - name: Set up Python
        # Prepare Python on the runner. This does not change the student laptop.
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Run tests
        # This is the key verification step in the CI workflow.
        run: python -m unittest discover -s tests -v
   build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Run tests
        run: python -m unittest discover -s tests -v

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image tag
        id: tag
        run: |
          TAG="${GITHUB_SHA::7}"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:${{ steps.tag.outputs.tag }} .

      - name: Tag image for ECR
        run: |
          docker tag $IMAGE_NAME:${{ steps.tag.outputs.tag }} \
          ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ steps.tag.outputs.tag }}

      - name: Push image to ECR
        run: |
          docker push \
          ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ steps.tag.outputs.tag }}
